### ISSUE TITLE
Add download counters per file and per application

### ISSUE THREAD

**Issue by sgdc3** [MCMirror/MCMirror#14]

**Comment by fionera** [comment]
How should i store the information? I dont want to add a DB

**Comment by sgdc3** [comment]
what about making it optional? the counters will be shown only if enabled

**Comment by fionera** [comment]
still no solution for the storage

**Comment by krusic22** [comment]
Since we need a SQL DB for Gitea we could probably use that.
But I don't really see a point in showing that kind of info since most users are here for the latest version of some jar. 
We could log it internally to see which files are worth keeping long term.

**Comment by kasuganosoras** [comment]
Maybe use the file to storaged? Use the json format.

**Comment by sgdc3** [comment]
not peeformant at all no pls

**Comment by sgdc3** [comment]
let's make it optional but use mysql

**Comment by fionera** [comment]
Done with https://github.com/MCMirror/MCMirror/commit/af3eb2881f7b5355a1f351e6388b5007a0588394
