### ISSUE TITLE
Help Initializing

### ISSUE THREAD

**Issue by josephworks** [MCMirror/MCMirror#15]
When I run the given command:

`php vendor/bin/ppm start --bootstrap=symfony --app-env=prod --logging=0 --debug=0 --workers=20 --static-directory=public/`

It returns:

`Could not open input file: vendor/bin/ppm`

**Comment by fionera** [comment]
You have to use composer to download the dependencies first

**Comment by josephworks** [comment]
how do i use that?

**Comment by fionera** [comment]
https://getcomposer.org/

**Comment by josephworks** [comment]
thanks! but shouldn't that be in the README.md?

**Comment by fionera** [comment]
Since this repo is made so that PHP developer etc. can help, I think its basic knowledge how to use Composer

**Comment by fionera** [comment]
You can always make a Pull-Request to add this :)

**Comment by josephworks** [comment]
Ok, I'm on it!
