### ISSUE TITLE
Non-External Links do not work

### ISSUE THREAD

**Issue by josephworks** [MCMirror/MCMirror#31]
Any Project that is using a Non-External Link Returns the error:

![image](https://user-images.githubusercontent.com/18745823/48656794-fc555200-e9e6-11e8-8b0d-bafbb0cdb79e.png)

Without these Non-External Sites, MC Mirror is not a Mirror

**Comment by sgdc3** [comment]
They work :/  https://mcmirror.io/grab/Paper/PaperSpigot-latest.jar Are you sure this isn't your local dev environment?

**Comment by josephworks** [comment]
Yes, in fact, it was my dev env.
Is it possible to enable those sites?

**Comment by fionera** [comment]
You have to have the Files on your PC since the Backend looks them up on request
